// Generated by gencpp from file srv_msg_pkg/message.msg
// DO NOT EDIT!


#ifndef SRV_MSG_PKG_MESSAGE_MESSAGE_H
#define SRV_MSG_PKG_MESSAGE_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_msg_pkg
{
template <class ContainerAllocator>
struct message_
{
  typedef message_<ContainerAllocator> Type;

  message_()
    : A(0)  {
    }
  message_(const ContainerAllocator& _alloc)
    : A(0)  {
  (void)_alloc;
    }



   typedef int64_t _A_type;
  _A_type A;




  typedef boost::shared_ptr< ::srv_msg_pkg::message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_msg_pkg::message_<ContainerAllocator> const> ConstPtr;

}; // struct message_

typedef ::srv_msg_pkg::message_<std::allocator<void> > message;

typedef boost::shared_ptr< ::srv_msg_pkg::message > messagePtr;
typedef boost::shared_ptr< ::srv_msg_pkg::message const> messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_msg_pkg::message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_msg_pkg::message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srv_msg_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'srv_msg_pkg': ['/home/parallels/catkin_ws/src/srv_msg_pkg/msg', '/home/parallels/catkin_ws/src/srv_msg_pkg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srv_msg_pkg::message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_msg_pkg::message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_msg_pkg::message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_msg_pkg::message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_msg_pkg::message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_msg_pkg::message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_msg_pkg::message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cacada641c8116215aaa1be2ff0da518";
  }

  static const char* value(const ::srv_msg_pkg::message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcacada641c811621ULL;
  static const uint64_t static_value2 = 0x5aaa1be2ff0da518ULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_msg_pkg::message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_msg_pkg/message";
  }

  static const char* value(const ::srv_msg_pkg::message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_msg_pkg::message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message_type message_a\n\
int64 A\n\
\n\
";
  }

  static const char* value(const ::srv_msg_pkg::message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_msg_pkg::message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_msg_pkg::message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_msg_pkg::message_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int64_t>::stream(s, indent + "  ", v.A);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_MSG_PKG_MESSAGE_MESSAGE_H
