// Generated by gencpp from file srv_msg_pkg/service.msg
// DO NOT EDIT!


#ifndef SRV_MSG_PKG_MESSAGE_SERVICE_H
#define SRV_MSG_PKG_MESSAGE_SERVICE_H

#include <ros/service_traits.h>


#include <srv_msg_pkg/serviceRequest.h>
#include <srv_msg_pkg/serviceResponse.h>


namespace srv_msg_pkg
{

struct service
{

typedef serviceRequest Request;
typedef serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct service
} // namespace srv_msg_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_msg_pkg::service > {
  static const char* value()
  {
    return "0470c3378013a84929363e98282d0a0c";
  }

  static const char* value(const ::srv_msg_pkg::service&) { return value(); }
};

template<>
struct DataType< ::srv_msg_pkg::service > {
  static const char* value()
  {
    return "srv_msg_pkg/service";
  }

  static const char* value(const ::srv_msg_pkg::service&) { return value(); }
};


// service_traits::MD5Sum< ::srv_msg_pkg::serviceRequest> should match 
// service_traits::MD5Sum< ::srv_msg_pkg::service > 
template<>
struct MD5Sum< ::srv_msg_pkg::serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_msg_pkg::service >::value();
  }
  static const char* value(const ::srv_msg_pkg::serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_msg_pkg::serviceRequest> should match 
// service_traits::DataType< ::srv_msg_pkg::service > 
template<>
struct DataType< ::srv_msg_pkg::serviceRequest>
{
  static const char* value()
  {
    return DataType< ::srv_msg_pkg::service >::value();
  }
  static const char* value(const ::srv_msg_pkg::serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_msg_pkg::serviceResponse> should match 
// service_traits::MD5Sum< ::srv_msg_pkg::service > 
template<>
struct MD5Sum< ::srv_msg_pkg::serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_msg_pkg::service >::value();
  }
  static const char* value(const ::srv_msg_pkg::serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_msg_pkg::serviceResponse> should match 
// service_traits::DataType< ::srv_msg_pkg::service > 
template<>
struct DataType< ::srv_msg_pkg::serviceResponse>
{
  static const char* value()
  {
    return DataType< ::srv_msg_pkg::service >::value();
  }
  static const char* value(const ::srv_msg_pkg::serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_MSG_PKG_MESSAGE_SERVICE_H
