// Generated by gencpp from file srv_msg_practice_pkg/vision_service.msg
// DO NOT EDIT!


#ifndef SRV_MSG_PRACTICE_PKG_MESSAGE_VISION_SERVICE_H
#define SRV_MSG_PRACTICE_PKG_MESSAGE_VISION_SERVICE_H

#include <ros/service_traits.h>


#include <srv_msg_practice_pkg/vision_serviceRequest.h>
#include <srv_msg_practice_pkg/vision_serviceResponse.h>


namespace srv_msg_practice_pkg
{

struct vision_service
{

typedef vision_serviceRequest Request;
typedef vision_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct vision_service
} // namespace srv_msg_practice_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_msg_practice_pkg::vision_service > {
  static const char* value()
  {
    return "b03fb3535cd4e6d95a09f7a1ee4ed4f2";
  }

  static const char* value(const ::srv_msg_practice_pkg::vision_service&) { return value(); }
};

template<>
struct DataType< ::srv_msg_practice_pkg::vision_service > {
  static const char* value()
  {
    return "srv_msg_practice_pkg/vision_service";
  }

  static const char* value(const ::srv_msg_practice_pkg::vision_service&) { return value(); }
};


// service_traits::MD5Sum< ::srv_msg_practice_pkg::vision_serviceRequest> should match 
// service_traits::MD5Sum< ::srv_msg_practice_pkg::vision_service > 
template<>
struct MD5Sum< ::srv_msg_practice_pkg::vision_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_msg_practice_pkg::vision_service >::value();
  }
  static const char* value(const ::srv_msg_practice_pkg::vision_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_msg_practice_pkg::vision_serviceRequest> should match 
// service_traits::DataType< ::srv_msg_practice_pkg::vision_service > 
template<>
struct DataType< ::srv_msg_practice_pkg::vision_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::srv_msg_practice_pkg::vision_service >::value();
  }
  static const char* value(const ::srv_msg_practice_pkg::vision_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_msg_practice_pkg::vision_serviceResponse> should match 
// service_traits::MD5Sum< ::srv_msg_practice_pkg::vision_service > 
template<>
struct MD5Sum< ::srv_msg_practice_pkg::vision_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_msg_practice_pkg::vision_service >::value();
  }
  static const char* value(const ::srv_msg_practice_pkg::vision_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_msg_practice_pkg::vision_serviceResponse> should match 
// service_traits::DataType< ::srv_msg_practice_pkg::vision_service > 
template<>
struct DataType< ::srv_msg_practice_pkg::vision_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::srv_msg_practice_pkg::vision_service >::value();
  }
  static const char* value(const ::srv_msg_practice_pkg::vision_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_MSG_PRACTICE_PKG_MESSAGE_VISION_SERVICE_H
