// Generated by gencpp from file srv_msg_practice_pkg/vision_position.msg
// DO NOT EDIT!


#ifndef SRV_MSG_PRACTICE_PKG_MESSAGE_VISION_POSITION_H
#define SRV_MSG_PRACTICE_PKG_MESSAGE_VISION_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_msg_practice_pkg
{
template <class ContainerAllocator>
struct vision_position_
{
  typedef vision_position_<ContainerAllocator> Type;

  vision_position_()
    : x(0.0)
    , y(0.0)  {
    }
  vision_position_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> const> ConstPtr;

}; // struct vision_position_

typedef ::srv_msg_practice_pkg::vision_position_<std::allocator<void> > vision_position;

typedef boost::shared_ptr< ::srv_msg_practice_pkg::vision_position > vision_positionPtr;
typedef boost::shared_ptr< ::srv_msg_practice_pkg::vision_position const> vision_positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srv_msg_practice_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'srv_msg_practice_pkg': ['/home/parallels/catkin_ws/src/rosPractice/srv_msg_practice_pkg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::srv_msg_practice_pkg::vision_position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_msg_practice_pkg/vision_position";
  }

  static const char* value(const ::srv_msg_practice_pkg::vision_position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::srv_msg_practice_pkg::vision_position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vision_position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_msg_practice_pkg::vision_position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_msg_practice_pkg::vision_position_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_MSG_PRACTICE_PKG_MESSAGE_VISION_POSITION_H
