(cl:defpackage srv_msg_practice_pkg-srv
  (:use )
  (:export
   "CONTROL_SERVICE"
   "<CONTROL_SERVICE-REQUEST>"
   "CONTROL_SERVICE-REQUEST"
   "<CONTROL_SERVICE-RESPONSE>"
   "CONTROL_SERVICE-RESPONSE"
   "VISION_SERVICE"
   "<VISION_SERVICE-REQUEST>"
   "VISION_SERVICE-REQUEST"
   "<VISION_SERVICE-RESPONSE>"
   "VISION_SERVICE-RESPONSE"
  ))

